### PR TITLE
BayesSpace v1.11.0

### PR DESCRIPTION
**Pull request by senbaikang**
This update focuses on performance enhancement, including:

1. The function loading data from Space Ranger outputs, `readVisium`, is now compatible with both new (>=V2.0) and old (<V2.0) Space Ranger.
2. A new function, `read10Xh5`, is added so that HDF5 data from 10X can be directly loaded.
3. The function to determine the number of clusters, `qTune`, can now be run with multiple threads. With a seed set, the results are invariate to the number of threads used.
4. The underlying C++ code for resolution enhancement has been accelerated with multithreading and a faster function to compute the density of multivariate normal distributions. Compared to v1.8.2, the run time is cut by around a half. With a seed set, the results are invariate to the number of threads used.

Note that to install this version of BayesSpace `libomp` is required.

### CODE REVIEW

**Comment by edward130603** [comment]
@senbaikang I tried running the qTune code and it seems to just get stuck. For reference, the old version completed within a few seconds. 

```r
library(BayesSpace)
library(tictoc)
sce <- getRDS("2018_thrane_melanoma", "ST_mel1_rep2", cache=FALSE)
set.seed(100)
sce = spatialPreprocess(sce, platform = "ST", n.PCs = 7)
tic()
sce = qTune(sce, cores = 5)
toc()
qPlot(sce)
```

**Comment by edward130603** [comment]
Multiple cores did work for `spatialEnhance`. However results do not seem to match previous:

Old:
image

New (left, cores = 1; right, cores = 3):
image

Results also not exactly the same but less obviously different for `spatialCluster`.

Beyond this, do you have guidance on how to set # of cores? More = better or up to a certain number?

**Comment by senbaikang** [comment]
> @senbaikang I tried running the qTune code and it seems to just get stuck. For reference, the old version completed within a few seconds.
> 
> ```r
> library(BayesSpace)
> library(tictoc)
> sce <- getRDS("2018_thrane_melanoma", "ST_mel1_rep2", cache=FALSE)
> set.seed(100)
> sce = spatialPreprocess(sce, platform = "ST", n.PCs = 7)
> tic()
> sce = qTune(sce, cores = 5)
> toc()
> qPlot(sce)
> ```

Thank you for testing the code! I just had time to rerun your code above, and it finished in around 1 sec on my laptop, while the old version finished in around 3 sec in the same environment. Would you please reinstall the package and have a look at it again? We can also have a quick meeting to sort it out.

**Comment by senbaikang** [comment]
> Multiple cores did work for `spatialEnhance`. However results do not seem to match previous:
> 
> Old: image
> 
> New (left, cores = 1; right, cores = 3): image
> 
> Results also not exactly the same but less obviously different for `spatialCluster`.
> 
> Beyond this, do you have guidance on how to set # of cores? More = better or up to a certain number?

It is expected that the results of enhancement from the old and new version are different even with the seed set, as I had to rearrange some of the code to maximize efficiency. However, they should be the same for the new version with different number of threads used, as in each iteration of the MCMC the proposals are made before multi-threading are activated.

For the guidance of the number of cores to use, it depends on the number of PCs and the device. I think you can always run a small number of iterations with different numbers of cores, and compare the run time in a plot. It will first decrease (nearly) linearly, and then becomes flat. The "elbow" of the plot should be the number of cores you aim to.

**Comment by edward130603** [comment]
Thanks Senbai. I reinstalled and was able to get qTune to work with multiple cores.

Regarding the spatialEnhance results, I understand that the results are the same regardless of # of cores. However, my concern is that the results look substantially different from the original results using v1.6.0 of BayesSpace. It does not seem to just be a seed issue from what I can tell, since there's a lot less smoothing it seems. I can look into it a bit more later this week, but let me know if you figure it out before then.

**Comment by senbaikang** [comment]
Edward,

I have fixed the problem. Below is some plots of `spatialEnhance` from both old and new versions:

Old:
old_enhanced

New (top, cores = 1; bottom, cores = 4):
new_enhanced_1

new_enhanced_4

Please have a look again :)

**Comment by edward130603** [comment]
thanks Senbai, looks good now. 

I'll check again to make sure it looks good from bioconductor

**Pull request merged**
